import type { Metadata } from "next";
import "@/styles/globals.css";

import { Navbar } from "@/components/layout/navbar";

import { inter, mono, sans } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, sans.variable, mono.variable, "antialiased")}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
