import type { Metadata } from "next";
import "@/styles/globals.css";

import ReactLenis from "lenis/react";

import { BreakpointIndicator } from "@/components/dev/breakpoint-ind";
import { Footer } from "@/components/layout/footer";
import { Navbar } from "@/components/layout/navbar";

import { inter, mono, sans } from "@/assets/fonts";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.variable, sans.className, mono.variable, "antialiased")}>
        <Navbar />
        <ReactLenis root>{children}</ReactLenis>
        <Footer />
        <BreakpointIndicator />
      </body>
    </html>
  );
}
