import Link from "next/link";

import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

import { Header } from "../components/header";
import { SectionTitle } from "../components/section-title";
import { TableOfContent } from "../components/table-of-content";

const invoices = [
  {
    title: "Service",
    value: "The Sphere IT Global website and any related web services operated by Sphere IT.",
  },
  {
    title: "Personal Data",
    value:
      "Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).",
  },
  {
    title: "Usage Data",
    value:
      "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    title: "Cookies",
    value:
      "Small files stored on your device (computer or mobile device) used to improve website functionality and user experience.",
  },
  {
    title: "Data Controller",
    value:
      "A natural or legal person who (alone or jointly with others) determines the purposes and means of processing any personal data. For the purposes of this Privacy Policy, Sphere IT Global is the Data Controller of your data.",
  },
  {
    title: "Data Processors (or Service Providers)",
    value:
      "Any natural or legal person who processes data on behalf of the Data Controller. We may use the services of trusted third-party providers to process your data more effectively (e.g., website hosting).",
  },
  {
    title: "Data Subject",
    value: "Any living individual who is the subject of Personal Data.",
  },
  {
    title: "User",
    value:
      "The individual using our Service - this corresponds to the Data Subject, who is the subject of Personal Data.",
  },
];

export default function TermsOfServicesPage() {
  return (
    <main>
      <Header title="Terms of Service" />
      <section className="container grid max-w-7xl grid-cols-4 gap-12">
        <TableOfContent />
        <article className="prose prose-stone col-span-3 max-w-none border-l px-12 py-12">
          <div>
            <p>Welcome to Sphere IT Global ("Sphere IT", "we", "our", or "us").</p>
            <p>
              Sphere IT provides technology, consulting, automation, and integration solutions to enterprises worldwide
              (the "Services").
            </p>
            <p>
              We value your privacy and are committed to protecting your personal data. This Privacy Policy explains how
              we collect, use, and protect information when you visit our website, communicate with us, or use our
              Services.
            </p>
            <p>
              By using our website or submitting your information through our contact forms, you agree to the practices
              described in this Privacy Policy.
            </p>
          </div>
          <div className="-mb-4 relative pt-4">
            <div className="relative">
              <div className="absolute top-0 bottom-0 left-4 w-px bg-stone-300" />
              <SectionTitle href="#definitions" index={1}>
                Definitions
              </SectionTitle>
              <div className="ml-12 pb-4">
                <p>Below is a list of definitions for the terms used in this Privacy Policy:</p>
                <Table className="max-w-screen">
                  <TableHeader>
                    <TableRow>
                      <TableHead>Term</TableHead>
                      <TableHead>Definition</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {invoices.map((invoice) => (
                      <TableRow key={invoice.title}>
                        <TableCell className="font-display text-subhead-base">{invoice.title}</TableCell>
                        <TableCell className="max-w-4xl text-base">{invoice.value}</TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
              <SectionTitle href="#information-collection" index={2}>
                Information We Collect
              </SectionTitle>
              <div className="ml-12 pb-4">
                <p>
                  We collect several different types of information for various purposes to provide and improve our
                  Service to you.
                </p>
                <h3 id="personal-data">Personal Data</h3>
                <p>
                  While using our Service, we may ask you to provide us with certain personally identifiable information
                  that can be used to contact or identify you (“Personal Data”). Personally identifiable information may
                  include, but is not limited to:
                </p>
                <ul>
                  <li>Your Name</li>
                  <li>Your Email Address</li>
                  <li>Your Phone Number</li>
                  <li>The Subject and Message you submit</li>
                </ul>
                <p>
                  We may use your Personal Data to contact you with newsletters, marketing or promotional materials and
                  other information that may be of interest to you. You may opt out of receiving any, or all, of these
                  communications from us by following the unsubscribe link or by emailing at{" "}
                  <Link href="mailto:info@sphereitglobal.com">info@sphereitglobal.com</Link>
                </p>
                <h3 id="usage-data">Usage Data</h3>
                <p>
                  We may also collect information that your browser sends whenever you visit our Service or when you
                  access Service by or through a mobile device (“Usage Data”).
                </p>
                <p>
                  This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP
                  address), browser type, browser version, the pages of our Service that you visit, the time and date of
                  your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                </p>
                <p>
                  When you access Service with a mobile device, this Usage Data may include information such as the type
                  of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your
                  mobile operating system, the type of mobile Internet browser you use, unique device identifiers and
                  other diagnostic data.
                </p>
              </div>
            </div>
          </div>
        </article>
      </section>
    </main>
  );
}
