/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    services: Service;
    blogs: Blog;
    blogCategories: BlogCategory;
    'case-studies': CaseStudy;
    researchPapers: ResearchPaper;
    faqs: Faq;
    'faq-categories': FaqCategory;
    'ai-maturity-submissions': AiMaturitySubmission;
    enquiries: Enquiry;
    media: Media;
    careers: Career;
    departments: Department;
    employeeTestimonials: EmployeeTestimonial;
    industries: Industry;
    partners: Partner;
    clients: Client;
    users: User;
    sessions: Session;
    accounts: Account;
    verifications: Verification;
    passkeys: Passkey;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    services: ServicesSelect<false> | ServicesSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    blogCategories: BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    researchPapers: ResearchPapersSelect<false> | ResearchPapersSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'faq-categories': FaqCategoriesSelect<false> | FaqCategoriesSelect<true>;
    'ai-maturity-submissions': AiMaturitySubmissionsSelect<false> | AiMaturitySubmissionsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    careers: CareersSelect<false> | CareersSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    employeeTestimonials: EmployeeTestimonialsSelect<false> | EmployeeTestimonialsSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    sessions: SessionsSelect<false> | SessionsSelect<true>;
    accounts: AccountsSelect<false> | AccountsSelect<true>;
    verifications: VerificationsSelect<false> | VerificationsSelect<true>;
    passkeys: PasskeysSelect<false> | PasskeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'services-page': ServicesPage;
    'about-page': AboutPage;
    'faqs-page': FaqsPage;
    'insights-page': InsightsPage;
    'methodology-page': MethodologyPage;
    teams: Team;
    footer: Footer;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'faqs-page': FaqsPageSelect<false> | FaqsPageSelect<true>;
    'insights-page': InsightsPageSelect<false> | InsightsPageSelect<true>;
    'methodology-page': MethodologyPageSelect<false> | MethodologyPageSelect<true>;
    teams: TeamsSelect<false> | TeamsSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  _order?: string | null;
  service: string;
  heroImage: number | Media;
  title: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  ctaButtons?:
    | {
        link: {
          type?: ('page' | 'reference' | 'custom') | null;
          newTab?: boolean | null;
          page?:
            | (
                | '/'
                | '/services'
                | '/about'
                | '/resources/blogs'
                | '/resources/case-studies'
                | '/resources/research-papers'
                | '/resources/faqs'
                | '/careers'
                | '/contact'
                | '/methodology'
                | '/resources/ai-maturity'
              )
            | null;
          reference?:
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null)
            | ({
                relationTo: 'blogs';
                value: number | Blog;
              } | null)
            | ({
                relationTo: 'case-studies';
                value: number | CaseStudy;
              } | null)
            | ({
                relationTo: 'researchPapers';
                value: number | ResearchPaper;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  partners?: (number | Partner)[] | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  homepage: {
    title: string;
    description: string;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    tags?:
      | {
          tag: string;
          id?: string | null;
        }[]
      | null;
    proofLink?: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label?: string | null;
      /**
       * Choose how the link should be rendered.
       */
      appearance?: ('default' | 'outline') | null;
    };
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  title: string;
  description: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  isFeatured?: boolean | null;
  relatedPosts?: (number | Blog)[] | null;
  blogCategories?: (number | BlogCategory)[] | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories".
 */
export interface BlogCategory {
  id: number;
  category: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  email: string;
  emailVerified?: boolean | null;
  name?: string | null;
  image?: string | null;
  role?: ('user' | 'editor' | 'admin') | null;
  updatedAt: string;
  createdAt: string;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  highlights?:
    | {
        value?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  relatedStudies?: (number | CaseStudy)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researchPapers".
 */
export interface ResearchPaper {
  id: number;
  title: string;
  heroImage?: (number | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  relatedResearchPapers?: (number | ResearchPaper)[] | null;
  authors?: (number | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  _order?: string | null;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  content: string;
  category?: (number | null) | FaqCategory;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories".
 */
export interface FaqCategory {
  id: number;
  category: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-maturity-submissions".
 */
export interface AiMaturitySubmission {
  id: number;
  name: string;
  email: string;
  company: string;
  phone?: string | null;
  /**
   * 1. Do you have a clear AI strategy aligned to measurable business outcomes?
   */
  q1: number;
  /**
   * 2. Has C level leadership formally approved and endorsed the AI strategy?
   */
  q2: number;
  /**
   * 3. Are success metrics for AI initiatives defined and tracked
   */
  q3: number;
  /**
   * 4. Are there a dedicated AI budget for the coming financial year?
   */
  q4: number;
  /**
   * 5. Are business leaders accountable for driving AI adoption in their areas?
   */
  q5: number;
  /**
   * 6.	Is your enterprise data catalogued, classified, and easily searchable?
   */
  q6: number;
  /**
   * 7. How confident are you in data accuracy, completeness, and lineage?
   */
  q7: number;
  /**
   * 8.	Do you have a unified data platform that supports analytics and AI?
   */
  q8: number;
  /**
   * 9.	Are data access controls and residency rules aligned with regulatory expectations?
   */
  q9: number;
  /**
   * 10.	Can teams reliably access clean governed datasets for AI and ML work?
   */
  q10: number;
  /**
   * 11.	Do you have a clear and approved policy for LLM and generative AI usage?
   */
  q11: number;
  /**
   * 12.	Is your current infrastructure capable of handling AI workloads at scale?
   */
  q12: number;
  /**
   * 13.	Are you using MLOps or AIOps for model lifecycle and deployment management?
   */
  q13: number;
  /**
   * 14.	Do you have an AI governance framework with controls for privacy and bias?
   */
  q14: number;
  /**
   * 15.	Are employees trained on responsible AI practices and escalation routes?
   */
  q15: number;
  /**
   * Total questionnaire score
   */
  totalScore: number;
  /**
   * Maturity percentage
   */
  percentage: number;
  /**
   * Maturity level
   */
  level: 'Foundation' | 'Developing' | 'Progressive' | 'Advanced';
  /**
   * Level description
   */
  description: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * Subject (full contact form only)
   */
  subject?: string | null;
  message: string;
  /**
   * Page or context (e.g. route) for quick enquiries
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers".
 */
export interface Career {
  id: number;
  title: string;
  description?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  department?: (number | null) | Department;
  location?: string | null;
  time?: string | null;
  workMode?: ('on-site' | 'hybrid' | 'remote')[] | null;
  validUntil?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  department: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employeeTestimonials".
 */
export interface EmployeeTestimonial {
  id: number;
  name: string;
  jobRole?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  _order?: string | null;
  icon?: string | null;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  _order?: string | null;
  name: string;
  logo: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (session)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions".
 */
export interface Session {
  id: number;
  expiresAt: string;
  token: string;
  ipAddress?: string | null;
  userAgent?: string | null;
  user: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (account)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts".
 */
export interface Account {
  id: number;
  accountId: string;
  providerId: string;
  user: number | User;
  accessToken?: string | null;
  refreshToken?: string | null;
  idToken?: string | null;
  accessTokenExpiresAt?: string | null;
  refreshTokenExpiresAt?: string | null;
  scope?: string | null;
  password?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (verification)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications".
 */
export interface Verification {
  id: number;
  identifier: string;
  value: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Auto-generated from Better Auth schema (passkey)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys".
 */
export interface Passkey {
  id: number;
  name?: string | null;
  publicKey: string;
  user: number | User;
  credentialID: string;
  counter: number;
  deviceType: string;
  backedUp: boolean;
  transports?: string | null;
  aaguid?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'blogs';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'blogCategories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'researchPapers';
        value: number | ResearchPaper;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'faq-categories';
        value: number | FaqCategory;
      } | null)
    | ({
        relationTo: 'ai-maturity-submissions';
        value: number | AiMaturitySubmission;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'careers';
        value: number | Career;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'employeeTestimonials';
        value: number | EmployeeTestimonial;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'sessions';
        value: number | Session;
      } | null)
    | ({
        relationTo: 'accounts';
        value: number | Account;
      } | null)
    | ({
        relationTo: 'verifications';
        value: number | Verification;
      } | null)
    | ({
        relationTo: 'passkeys';
        value: number | Passkey;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  _order?: T;
  service?: T;
  heroImage?: T;
  title?: T;
  description?: T;
  ctaButtons?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  partners?: T;
  content?: T;
  homepage?:
    | T
    | {
        title?: T;
        description?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        tags?:
          | T
          | {
              tag?: T;
              id?: T;
            };
        proofLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  heroImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  isFeatured?: T;
  relatedPosts?: T;
  blogCategories?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogCategories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  category?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  highlights?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  relatedStudies?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "researchPapers_select".
 */
export interface ResearchPapersSelect<T extends boolean = true> {
  title?: T;
  heroImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  relatedResearchPapers?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  content?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-categories_select".
 */
export interface FaqCategoriesSelect<T extends boolean = true> {
  category?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-maturity-submissions_select".
 */
export interface AiMaturitySubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  q1?: T;
  q2?: T;
  q3?: T;
  q4?: T;
  q5?: T;
  q6?: T;
  q7?: T;
  q8?: T;
  q9?: T;
  q10?: T;
  q11?: T;
  q12?: T;
  q13?: T;
  q14?: T;
  q15?: T;
  totalScore?: T;
  percentage?: T;
  level?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "careers_select".
 */
export interface CareersSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  department?: T;
  location?: T;
  time?: T;
  workMode?: T;
  validUntil?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  department?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employeeTestimonials_select".
 */
export interface EmployeeTestimonialsSelect<T extends boolean = true> {
  name?: T;
  jobRole?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  _order?: T;
  icon?: T;
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  logo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  email?: T;
  emailVerified?: T;
  name?: T;
  image?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sessions_select".
 */
export interface SessionsSelect<T extends boolean = true> {
  expiresAt?: T;
  token?: T;
  ipAddress?: T;
  userAgent?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accounts_select".
 */
export interface AccountsSelect<T extends boolean = true> {
  accountId?: T;
  providerId?: T;
  user?: T;
  accessToken?: T;
  refreshToken?: T;
  idToken?: T;
  accessTokenExpiresAt?: T;
  refreshTokenExpiresAt?: T;
  scope?: T;
  password?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verifications_select".
 */
export interface VerificationsSelect<T extends boolean = true> {
  identifier?: T;
  value?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passkeys_select".
 */
export interface PasskeysSelect<T extends boolean = true> {
  name?: T;
  publicKey?: T;
  user?: T;
  credentialID?: T;
  counter?: T;
  deviceType?: T;
  backedUp?: T;
  transports?: T;
  aaguid?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
  };
  services: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    cta: {
      enable: boolean;
      title?: string | null;
      link?: {
        type?: ('page' | 'reference' | 'custom') | null;
        newTab?: boolean | null;
        page?:
          | (
              | '/'
              | '/services'
              | '/about'
              | '/resources/blogs'
              | '/resources/case-studies'
              | '/resources/research-papers'
              | '/resources/faqs'
              | '/careers'
              | '/contact'
              | '/methodology'
              | '/resources/ai-maturity'
            )
          | null;
        reference?:
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null)
          | ({
              relationTo: 'case-studies';
              value: number | CaseStudy;
            } | null)
          | ({
              relationTo: 'researchPapers';
              value: number | ResearchPaper;
            } | null);
        url?: string | null;
        label: string;
      };
    };
  };
  industries: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description?: string | null;
    items?: (number | Industry)[] | null;
  };
  whyUs: {
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    guidedByCard: {
      badge?: string | null;
      title: string;
      description: string;
    };
    axisCard: {
      title: string;
      learnMoreLink: {
        type?: ('page' | 'reference' | 'custom') | null;
        newTab?: boolean | null;
        page?:
          | (
              | '/'
              | '/services'
              | '/about'
              | '/resources/blogs'
              | '/resources/case-studies'
              | '/resources/research-papers'
              | '/resources/faqs'
              | '/careers'
              | '/contact'
              | '/methodology'
              | '/resources/ai-maturity'
            )
          | null;
        reference?:
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null)
          | ({
              relationTo: 'case-studies';
              value: number | CaseStudy;
            } | null)
          | ({
              relationTo: 'researchPapers';
              value: number | ResearchPaper;
            } | null);
        url?: string | null;
        label: string;
      };
      phases?:
        | {
            letter: string;
            title: string;
            description: string;
            id?: string | null;
          }[]
        | null;
    };
    techStackCard: {
      badge?: string | null;
      title: string;
      ctaLink: {
        type?: ('page' | 'reference' | 'custom') | null;
        newTab?: boolean | null;
        page?:
          | (
              | '/'
              | '/services'
              | '/about'
              | '/resources/blogs'
              | '/resources/case-studies'
              | '/resources/research-papers'
              | '/resources/faqs'
              | '/careers'
              | '/contact'
              | '/methodology'
              | '/resources/ai-maturity'
            )
          | null;
        reference?:
          | ({
              relationTo: 'services';
              value: number | Service;
            } | null)
          | ({
              relationTo: 'blogs';
              value: number | Blog;
            } | null)
          | ({
              relationTo: 'case-studies';
              value: number | CaseStudy;
            } | null)
          | ({
              relationTo: 'researchPapers';
              value: number | ResearchPaper;
            } | null);
        url?: string | null;
        label: string;
      };
    };
    reliabilityCard: {
      title: string;
    };
    miniCta: {
      title: string;
      description: string;
    };
  };
  cta: {
    badge?: string | null;
    /**
     * Check to show the enquiry form in the CTA
     */
    showForm?: boolean | null;
    title: string;
    description?: string | null;
    link: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  hero: {
    badge: string;
    /**
     * Main heading. Use bold or accent color for the highlighted phrase (e.g. “Automation to Augmentation”).
     */
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    subtitle: string;
    description: string;
  };
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero: {
    badge: string;
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  story: {
    badge: string;
    content: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
  };
  values: {
    badge: string;
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    items?:
      | {
          image: number | Media;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  team: {
    badge: string;
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    leadershipLabel: string;
    teamLabel: string;
  };
  hiring: {
    badge: string;
    title: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description: string;
    ctaLink: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label: string;
    };
    benefits?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  cta?: {
    /**
     * Check to show the enquiry form in the CTA
     */
    showForm?: boolean | null;
  };
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs-page".
 */
export interface FaqsPage {
  id: number;
  header: {
    /**
     * Badge text shown above the heading.
     */
    badge: string;
    /**
     * Main heading shown in accent color.
     */
    titleHighlight: string;
    /**
     * Secondary line below the heading.
     */
    titleSuffix: string;
  };
  cta: {
    badge?: string | null;
    title: string;
    description?: string | null;
    showForm?: boolean | null;
    buttonText?: string | null;
    /**
     * Button link destination.
     */
    link: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-page".
 */
export interface InsightsPage {
  id: number;
  header: {
    /**
     * Text before the highlighted company name.
     */
    titlePrefix: string;
    /**
     * Company name shown in accent color.
     */
    titleHighlight: string;
    subtitle: string;
  };
  cta: {
    badge?: string | null;
    title: string;
    description?: string | null;
    showForm?: boolean | null;
    buttonText?: string | null;
    /**
     * Button link destination.
     */
    link: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "methodology-page".
 */
export interface MethodologyPage {
  id: number;
  hero: {
    title: string;
    subtitle: string;
    ctaLink?: {
      type?: ('page' | 'reference' | 'custom') | null;
      newTab?: boolean | null;
      page?:
        | (
            | '/'
            | '/services'
            | '/about'
            | '/resources/blogs'
            | '/resources/case-studies'
            | '/resources/research-papers'
            | '/resources/faqs'
            | '/careers'
            | '/contact'
            | '/methodology'
            | '/resources/ai-maturity'
          )
        | null;
      reference?:
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null)
        | ({
            relationTo: 'blogs';
            value: number | Blog;
          } | null)
        | ({
            relationTo: 'case-studies';
            value: number | CaseStudy;
          } | null)
        | ({
            relationTo: 'researchPapers';
            value: number | ResearchPaper;
          } | null);
      url?: string | null;
      label?: string | null;
    };
    image?: (number | null) | Media;
  };
  valueProposition: {
    badge: string;
    heading: string;
    description: string;
  };
  phases?: {
    items?:
      | {
          icon: 'bullseye' | 'search' | 'rocket' | 'shield';
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
  };
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams".
 */
export interface Team {
  id: number;
  leaderships?:
    | {
        picture: number | Media;
        name: string;
        position: string;
        linkedinUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  members?:
    | {
        picture: number | Media;
        name: string;
        position: string;
        linkedinUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  description: string;
  socials?:
    | {
        platform?: ('facebook' | 'instagram' | 'linkedin' | 'youtube' | 'x') | null;
        link: string;
        id?: string | null;
      }[]
    | null;
  locations?:
    | {
        location: string;
        link: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        description?: T;
      };
  services?:
    | T
    | {
        title?: T;
        cta?:
          | T
          | {
              enable?: T;
              title?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    page?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
      };
  industries?:
    | T
    | {
        title?: T;
        description?: T;
        items?: T;
      };
  whyUs?:
    | T
    | {
        title?: T;
        description?: T;
        guidedByCard?:
          | T
          | {
              badge?: T;
              title?: T;
              description?: T;
            };
        axisCard?:
          | T
          | {
              title?: T;
              learnMoreLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    page?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              phases?:
                | T
                | {
                    letter?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
            };
        techStackCard?:
          | T
          | {
              badge?: T;
              title?: T;
              ctaLink?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    page?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
            };
        reliabilityCard?:
          | T
          | {
              title?: T;
            };
        miniCta?:
          | T
          | {
              title?: T;
              description?: T;
            };
      };
  cta?:
    | T
    | {
        badge?: T;
        showForm?: T;
        title?: T;
        description?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        subtitle?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
      };
  story?:
    | T
    | {
        badge?: T;
        content?: T;
      };
  values?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        items?:
          | T
          | {
              image?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  team?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        leadershipLabel?: T;
        teamLabel?: T;
      };
  hiring?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        ctaLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        benefits?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  cta?:
    | T
    | {
        showForm?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs-page_select".
 */
export interface FaqsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        badge?: T;
        titleHighlight?: T;
        titleSuffix?: T;
      };
  cta?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        showForm?: T;
        buttonText?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights-page_select".
 */
export interface InsightsPageSelect<T extends boolean = true> {
  header?:
    | T
    | {
        titlePrefix?: T;
        titleHighlight?: T;
        subtitle?: T;
      };
  cta?:
    | T
    | {
        badge?: T;
        title?: T;
        description?: T;
        showForm?: T;
        buttonText?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "methodology-page_select".
 */
export interface MethodologyPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaLink?:
          | T
          | {
              type?: T;
              newTab?: T;
              page?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        image?: T;
      };
  valueProposition?:
    | T
    | {
        badge?: T;
        heading?: T;
        description?: T;
      };
  phases?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teams_select".
 */
export interface TeamsSelect<T extends boolean = true> {
  leaderships?:
    | T
    | {
        picture?: T;
        name?: T;
        position?: T;
        linkedinUrl?: T;
        id?: T;
      };
  members?:
    | T
    | {
        picture?: T;
        name?: T;
        position?: T;
        linkedinUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  description?: T;
  socials?:
    | T
    | {
        platform?: T;
        link?: T;
        id?: T;
      };
  locations?:
    | T
    | {
        location?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'researchPapers';
          value: number | ResearchPaper;
        } | null)
      | ({
          relationTo: 'careers';
          value: number | Career;
        } | null)
      | ({
          relationTo: 'employeeTestimonials';
          value: number | EmployeeTestimonial;
        } | null);
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ButtonBlock".
 */
export interface ButtonBlock {
  style: 'default' | 'secondary' | 'outline' | 'ghost' | 'link';
  size?: ('default' | 'sm' | 'lg') | null;
  link: {
    type?: ('page' | 'reference' | 'custom') | null;
    newTab?: boolean | null;
    page?:
      | (
          | '/'
          | '/services'
          | '/about'
          | '/resources/blogs'
          | '/resources/case-studies'
          | '/resources/research-papers'
          | '/resources/faqs'
          | '/careers'
          | '/contact'
          | '/methodology'
          | '/resources/ai-maturity'
        )
      | null;
    reference?:
      | ({
          relationTo: 'services';
          value: number | Service;
        } | null)
      | ({
          relationTo: 'blogs';
          value: number | Blog;
        } | null)
      | ({
          relationTo: 'case-studies';
          value: number | CaseStudy;
        } | null)
      | ({
          relationTo: 'researchPapers';
          value: number | ResearchPaper;
        } | null);
    url?: string | null;
    label: string;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'button';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: number | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardBlock".
 */
export interface CardBlock {
  style: 'basic' | 'outlined';
  columns?: ('2' | '3' | '4') | null;
  cards?:
    | {
        /**
         * Choose an icon to display with this card.
         */
        icon?: string | null;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'card';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ListBlock".
 */
export interface ListBlock {
  style: 'default';
  columns?: ('2' | '3' | '4') | null;
  items?:
    | {
        title: string;
        description: string;
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'list';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CertificationsBlock".
 */
export interface CertificationsBlock {
  title: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  industries?:
    | (
        | 'retail-banking'
        | 'corporate-banking'
        | 'wealth-management'
        | 'insurance'
        | 'conglomerates'
        | 'government-entities'
        | 'telecommunications'
        | 'energy-utilities'
      )[]
    | null;
  certifications?:
    | {
        title: string;
        /**
         * (Optional) Upload an icon for the certification. Recommended size: 200x200px
         */
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'certifications';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  content: string;
  link: string;
  linkText: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}