export const LEGAL_HANDLING_EMAIL = "info@sphereitglobal.com";

export const PRIVACY_DEFINITIONS = [
  {
    title: "Service",
    value: "The Sphere IT Global website and any related web services operated by Sphere IT.",
  },
  {
    title: "Personal Data",
    value:
      "Data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).",
  },
  {
    title: "Usage Data",
    value:
      "Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).",
  },
  {
    title: "Cookies",
    value:
      "Small files stored on your device (computer or mobile device) used to improve website functionality and user experience.",
  },
  {
    title: "Data Controller",
    value:
      "A natural or legal person who (alone or jointly with others) determines the purposes and means of processing any personal data. For the purposes of this Privacy Policy, Sphere IT Global is the Data Controller of your data.",
  },
  {
    title: "Data Processors (or Service Providers)",
    value:
      "Any natural or legal person who processes data on behalf of the Data Controller. We may use the services of trusted third-party providers to process your data more effectively (e.g., website hosting).",
  },
  {
    title: "Data Subject",
    value: "Any living individual who is the subject of Personal Data.",
  },
  {
    title: "User",
    value:
      "The individual using our Service - this corresponds to the Data Subject, who is the subject of Personal Data.",
  },
];

export const SERVICE_DEFINITIONS = [
  {
    title: "Service",
    value: "Sphere IT website and related services offered on www.sphereitglobal.com",
  },
  {
    title: "Personal Data",
    value: "Data about a living individual that can be identified from those data or combined with other information.",
  },
  {
    title: "Usage Data",
    value: "Data collected automatically, such as page visit duration.",
  },
  {
    title: "Cookies",
    value: "Small files stored on your device to improve your experience.",
  },
  {
    title: "Data Controller",
    value: "The entity determining how and why personal data is processed (Sphere IT).",
  },
  {
    title: "Data Processor",
    value: "Any party processing personal data on behalf of Sphere IT.",
  },
  {
    title: "User / Data Subject",
    value: "Any individual using the Site or submitting personal data.",
  },
];
